# This is a basic workflow to help you get started with Actions

name: Physician Conversion MLOPs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "Feature_Engineering_Pipeline"
  FTI_Pipeline:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
        max-parallel: 4
    
    env:
        AWS_ACCESS_KEY_ID : ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY : ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        HOPSWORKS_API_KEY : ${{ secrets.HOPSWORKS_API_KEY }}
        HOPSWORKS_PROJECT_NAME : ${{ secrets.HOPSWORKS_PROJECT_NAME }}


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Repo Checkout
        uses: actions/checkout@v2

      - name: Python Setup & Packages Installation
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Run the feature_pipeline workflow in a jobless fashion
        run: |
          python data_science/src/feature_pipeline.py

      - name: Run the training_pipeline workflow in a jobless fashion
        run: |
          python data_science/src/training_pipeline.py
